### ISSUE TITLE
smaller header

### ISSUE THREAD

**Issue by pjhalsli** [turing753/minimal-functional-fox#7]
I already asked this on reddit but no matter what I do I can't get it the way I want it.   Here's a pic of opera vs FF](https://imgur.com/a/NEBvfap)  as you can see the header in FF is much taller almost double the size.
What I want is the urlbar and the tabs right under so all this wasted space disappears.  Not sure if its even possible  Another thing when I minimized my tabs the new tab button disappeared. The button is still there but the plus sign is gone - and the button is only visible when I hover over it.
I've used nighttab for approx 8 months now and I was convinced it couldn't be any better than it was - you proved me wrong. This is truly the icing on the cake

**Comment by mut-ex** [comment]
For your new tab issue please take a look at the 5th bullet point in the instructions.

Other than that I can only suggest setting all the urlbar related CSS variables to 0 or as low as you can. That should reduce the height of the header area. Changes beyond that kind of fall outside the scope of what I created this configuration to look like. If the wasted space you are referring to is to the left of the urlbar between it and the back/forward buttons, it is there is because the urlbar has its contents centered and its width forced to a large value so that is in the middle. You can play around with the the selectors related to those properties to achieve the look you want.

**Comment by pjhalsli** [comment]
the wasted space I'm referring to is that I want the tabs closer to the urlbar - so there's not so much spoace between them.  I feel the header area is very high and thought if I got the tabs closer to the urlbar it woiuld be smaller?  I will continue to play around with it - I got it a little smaller but not as small as I want it..  Anyways - big thanks for this.  I thought zombiefox had invented perfection with nighttab but you actually improved it. So thank you

**Comment by pjhalsli** [comment]
for the plus sign to come back for the new tab - it seems one need to have the tabs a t least at 25 px height. Mine are at 18 atm and the plus sign won't appear.  This is no big issue for me thoug as I use ctrl -t for new tab and ctrl -w for closing tabs-. I use a tiling window manager so I'm, used to keybindings for everything.   If possible I could remove the whole new tab button altogether

**Comment by pjhalsli** [comment]
I got it to where I'm happy with it now so I'll close this.

**Comment by Amar1729** [comment]
@pjhalsli if you're still trying to decrease the height of the header, here are a couple things i did:

- decrease `--tab-height` and `--tabs-container-height` from 32, 140 to 27, 70, respectively
- decrease `--urlbar-container-margin` to 0
- decrease `--urlbar-text-size` to 12pt
- add some css for hiding the bookmarks bar: `#PersonalToolbar { display: none !important; }`
- decrease the `.browser-toolbar` `padding-top` to 1

You probably don't need to do all that depending on the look you're going for, but you can play around with those settings

**Comment by pjhalsli** [comment]
I got mine to look pretty neat actually - but thank you   :-)

edit: I tried your suggestions - and the toolbar-top setting really did the trick - now my FF looks exactly like I had hoped.  Thank you   :+1:
